### ISSUE TITLE
Description of the datasets

### ISSUE THREAD

**Issue by LouisSerrano** [pdebench/PDEBench#3]
Hi everyone, I came across your paper in the neurips dataset section and I was curious to check out your datasets, which could help me a lot formalize what angle I should take with my research.

But I was not sure which one to look at first, as there are many of them. Do you happen to have a description of the different datasets within a single family ? For instance, with incompressible Xavier stokes, what is the difference between the files `ns_incom_inhom_2d_512-0.h5`and `ns_incom_inhom_2d_512-100.h5` ?

Thanks for your help !

**Comment by timothypraditia** [comment]
Hi Louis, thank you for your interest. For each dataset we provide multiple samples, and in some cases these samples are separated across different files because the size is just too large. So to answer your question, they contain different samples, with the initial condition generated with different random seeds. I hope this answers your question, and sorry for the late response.
