### ISSUE TITLE
ModuleNotFoundError: No module named 'pdebench.models'

### ISSUE THREAD

**Issue by ningliu-iga** [pdebench/PDEBench#35]
Hi,

Great work! Thanks a lot for sharing your codes and dataset.

I have a problem with running the training code. The package worked fine on windows using pycharm, but when I installed it on linux and tried to run the train_models_forward.py, it kept giving me errors "ModuleNotFoundError: No module named 'pdebench.models'". I have tried to fix it using many online found solutions, such as adding an empty __init__.py file in the models subfolder, but none of them worked. Do you by any chance know how to resolve this issue?

BTW, I plotted the system path using print (sys.path), and did see the pdebench.models path there.

Many thanks,
Ning

**Comment by kmario23** [comment]
Hi @ningliu-iga,
  If you have downloaded the codebase to say the path `/home/ningliu/PDEBench/*`, then you can export this path so that it can be added to your PYTHONPATH which is where your python installation looks for the module.
  
`$ export PYTHONPATH="${PYTHONPATH}:/home/ningliu/PDEBench"`

If you want this to persist, then you can append the same to your bashrc.

---------

Alternatively, you can do `pip install .` to the downloaded repo, which will then automatically add the module to the python search path.
