### ISSUE TITLE
version matching | old issue-2023-09-24

### ISSUE THREAD

**Issue by Yangtze-flowing** [pdebench/PDEBench#59]
Sorry for this late post, I just got used to github
------
I found that in the "readme.md" of PDEbench, there's a section called "Configuring DeepXDE". However, according to DeepXDE, the required PyTorch version is 1.9.0 or later(Fig.1). But the latest version that pdebench supports is v1.13.0 (Fig.2). I wonder if there is something worth discussion.

![image](https://github.com/pdebench/PDEBench/assets/131173848/8a4e9f4e-9b47-48dd-85f9-f95656597421)
![image](https://github.com/pdebench/PDEBench/assets/131173848/61178879-2382-4176-87a3-118377e90b10)

**Comment by kmario23** [comment]
The codebase supports torch versions upto v1.13.1. If you're using v2.1.0 or later that should also work. The versions in-between the above two versions will most likely cause issues because of https://github.com/pytorch/pytorch/issues/65711.

Please let us know if you face problems in running the code, preferably with a traceback.
