### ISSUE TITLE
Any mistake in the initial condition of diffusion sorption 1d ?

### ISSUE THREAD

**Issue by myendless1** [pdebench/PDEBench#61]
I found that in the dataset of diffsorp1d, all the data at time t=0 are the same. Is this an error in the data, or is it intentional?

![image](https://github.com/pdebench/PDEBench/assets/63028914/857528d8-403c-45a1-9c65-405eacb6c5fd)

**Comment by kmario23** [comment]
This is because the initial condition is just a constant function. You can look at the detailed PDE description and the evolution profile in [section D.8 of the PDEBENCH paper](https://arxiv.org/pdf/2210.07182) as well as this snippet of code that [generates the initial condition `u0`](https://github.com/pdebench/PDEBench/blob/main/pdebench/data_gen/src/sim_diff_sorp.py#L74-L75).

```
# Generate initial condition
u0 = np.ones(self.Nx) * np.random.uniform(0,0.2)
```

Simply put, each sample trajectory in this dataset has a constant function as the initial condition, where the value for this constant is uniformly sampled in `(0, 0.2)` as shown above.
