### ISSUE TITLE
Question on the NS Equation

### ISSUE THREAD

**Issue by YCWangVince** [pdebench/PDEBench#9]
Thank you for your work on building this benchmark. 

When I checked the definition on both of your paper and the code, I see that for the compressible Navier-Stocks equation, the viscous stress tensor $\sigma'$, shear viscosity $\eta$ and bulk viscosity $\zeta$ shown in the paper are  not included in the pdes in the models/pinn/pde_definitions.py. 
Is that a mistake or just a normal settings?

Thank you!

**Comment by YCWangVince** [comment]
Also, I cannot find the definition of the incompressible NS equation in the code.

**Comment by mtakamoto-D** [comment]
Thank you for your kind feedback. 
The PINN training code for 2D/3D compressible NS equations has not been implemented. 
One reason is due to the disappointing results on 1D case so we did not feel it was not worth trying. 
For the moment we do not have a clear plan to implement them, but hopefully in the near future if requested.

**Comment by YCWangVince** [comment]
Got it. Looking forward to more implementations. Thank you!

**Comment by danmackinlay** [comment]
For the reference of others with this question, the invocation for the NS incompressible forward solver was

```shell
 ./gen_ns_incomp.py --multirun sim_name=ns_2d_incom_inhom_2d_512 label=ns_incomp_inhom_2d seed="range(0,250)" grid_size="[512,512]" n_batch=4
```
